### ISSUE TITLE
Please complete your profile

### ISSUE THREAD

**Issue by soharddbwarez** [HH-GAME-MM/HH-Club-Chat-Plus-Plus#1]
Just as a reminder to you that I'm waiting for you to do whatever you need to do here to enable the donation function so I can use GitHub to support you my friend.

Go Go Go, what the heck are you waiting for man.

Your friend Master Maximus

**Comment by HH-GAME-MM** [comment]
Hello Master!
As promised, I have now completed the profile. It is being reviewed by github right now.
Your friend,
-MM-

**Comment by soharddbwarez** [comment]
Nice work -MM-
I'll donate to you as soon as I see the button, I think that we have to wait until your application to receive donations goes through and accepted. I'm rooting for you buddy.

**Comment by HH-GAME-MM** [comment]
Hello Master

Thank you very much! I am closing this ticket as we have found a solution via patreon :)

https://www.patreon.com/HHMM

Your friend,
-MM-
